// Code generated by protoc-gen-hprose , DO NOT EDIT.
// source: hello.proto

package hello



// HelloService comment
type HelloService struct {
	// Hello method comment
	Hello func(input []byte) (out  []byte, error) `simple:"true"` // abc
}


// TestService comment
type TestService struct {
	Hello1 func(input []byte) (out  []byte, error) `simple:"true"` // Hello1 method comment
	Hello2 func(input []byte) (out  []byte, error) `simple:"true"`
}


// Block comment attached to
// DemoService.
type DemoService struct {
}

